version: '3.1'

services:
  app:
    build:
      context: ./app
    command: python -u main.py
    ports:
      - "80:80"
    volumes:
      - ./app:/opt/app
    environment:
      - "TZ=Europe/Paris"
volumes:
    notused:
    